"""Official-source funding catalogue checked on 2026-08-18."""
from __future__ import annotations


CATALOG_CALLS = (
    {
        "id": "navarra-digital-2026-a1",
        "funding_id": "NAV-DIGITAL-2026-A1",
        "organisation": "Gobierno de Navarra",
        "program": "Fomento de la empresa digital 2026",
        "call_name": "Implantación de soluciones tecnológicas digitales - Tipo A.1",
        "official_url": "https://www.navarra.es/es/tramites/on/-/line/ayudas-para-el-fomento-de-la-empresa-digital",
        "territory": "Navarra",
        "call_status": "OPEN",
        "opening_date": "2026-05-19",
        "closing_date": "2026-11-06",
        "beneficiaries": ["Empresas con establecimiento en Navarra y alta en IAE"],
        "technologies": ["ai", "industrial software", "automation", "digitalisation", "sensors"],
        "budget_min_eur": 5000,
        "grant_rate_pct": 35,
        "funding_rate_pct": 35,
        "max_aid_eur": 30000,
        "aid_types": ["Grant", "De minimis"],
        "advance_rate_pct": 0,
        "payment_timing": "Project must be completed, invoiced and paid before application",
        "liquidity_notes": "Requires full supplier pre-financing before the application; no advance is stated.",
        "eligible_costs": ["Consultoría", "Software no recurrente", "Hardware, sensores y automatismos hasta el 40%"],
        "required_documents": ["Memoria oficial A/B", "Evidencias de implantación", "Relación XLSX de gastos", "Facturas", "Justificantes bancarios de pago", "Declaración de transparencia cuando proceda"],
        "incentive_effect_required": False,
        "minimis": True,
        "official_verified": True,
        "verification_date": "2026-08-18",
    },
    {
        "id": "catalunya-accio-eu-rdi-coupon-2026",
        "funding_id": "ACCIO-COUPON-EU-RDI-2026",
        "organisation": "ACCIÓ",
        "program": "Cupons a la competitivitat empresarial",
        "call_name": "Cupón ACCIÓ para programas europeos de I+D+i",
        "official_url": "https://www.accio.gencat.cat/ca/serveis/cercador-ajuts-empresa/ajutsiserveis/26026-ACCIO-linia-cupons-programes-europeus-r-d-i",
        "territory": "Cataluña",
        "call_status": "OPEN",
        "opening_date": "2026-05-15",
        "closing_date": "2026-11-16",
        "beneficiaries": ["Empresas con establecimiento operativo en Cataluña"],
        "technologies": ["ai", "robotics", "industrial software", "automation", "r&d"],
        "budget_min_eur": 50000,
        "grant_rate_pct": 100,
        "funding_rate_pct": 100,
        "max_aid_eur": 12000,
        "aid_types": ["Grant", "De minimis"],
        "advance_rate_pct": 0,
        "payment_timing": "Payment subject to execution and justification",
        "liquidity_notes": "Funds accredited proposal preparation only, not engineering development or equipment.",
        "eligible_costs": ["Asesor acreditado ACCIÓ para preparar propuesta europea"],
        "required_documents": ["Solicitud electrónica", "Propuesta y presupuesto de asesor acreditado", "Declaración de minimis", "Justificación y evidencia de propuesta europea presentada"],
        "minimis": True,
        "official_verified": True,
        "verification_date": "2026-08-18",
    },
    {
        "id": "catalunya-accio-ai-coupon-2026",
        "funding_id": "ACCIO-COUPON-AI-2026",
        "organisation": "ACCIÓ",
        "program": "Cupons a la competitivitat empresarial",
        "call_name": "Cupón ACCIÓ de incorporación de IA",
        "official_url": "https://www.accio.gencat.cat/ca/serveis/cercador-ajuts-empresa/ajutsiserveis/26028-ACCIO-linia-incorporacio-ia",
        "territory": "Cataluña",
        "call_status": "CLOSED",
        "opening_date": "2026-05-15",
        "closing_date": "2026-07-30",
        "beneficiaries": ["Empresa de sector prioritario en Cataluña", "Más de 10 trabajadores", "Mínimo 2 años de vida"],
        "technologies": ["ai", "digitalisation"],
        "grant_rate_pct": 100,
        "funding_rate_pct": 100,
        "max_aid_eur": 8000,
        "aid_types": ["Grant", "De minimis"],
        "payment_timing": "Payment subject to execution and justification",
        "liquidity_notes": "Diagnostic advisory only; software, equipment and implementation are excluded.",
        "eligible_costs": ["Diagnóstico de IA por asesor acreditado ACCIÓ"],
        "required_documents": ["Solicitud electrónica", "Oferta de asesor acreditado", "Declaración de minimis", "Diagnóstico de IA para justificación"],
        "minimis": True,
        "official_verified": True,
        "verification_date": "2026-08-18",
    },
    {
        "id": "catalunya-tech-innovation-sme-2025",
        "funding_id": "ACCIO-TECH-INNOVATION-SME-2025",
        "organisation": "ACCIÓ",
        "program": "Innovación tecnológica de pymes FEDER",
        "call_name": "Proyectos de innovación tecnológica de pymes",
        "official_url": "https://www.accio.gencat.cat/ca/serveis/cercador-ajuts-empresa/ajutsiserveis/25205-ACCIO-subvencions-innovacio-tecnologica-pimes-feder",
        "territory": "Cataluña",
        "call_status": "CLOSED",
        "closing_date": "2025-07-22",
        "beneficiaries": ["Pymes con establecimiento operativo en Cataluña", "Mínimo 2 años de vida"],
        "technologies": ["ai", "industrial software", "automation", "green technology"],
        "budget_min_eur": 100000,
        "grant_rate_pct": 40,
        "funding_rate_pct": 40,
        "aid_types": ["Grant", "De minimis", "FEDER"],
        "eligible_costs": ["Colaboraciones externas", "Equipamiento nuevo", "Software y licencias"],
        "required_documents": ["Memoria técnica", "Presupuesto", "Declaraciones responsables", "Documentación de justificación FEDER"],
        "minimis": True,
        "official_verified": True,
        "verification_date": "2026-08-18",
    },
    {
        "id": "catalunya-productive-investment-2026",
        "funding_id": "CAT-PRODUCTIVE-INVESTMENT-2026",
        "organisation": "Dirección General de Industria de Cataluña",
        "program": "Inversiones productivas industriales",
        "call_name": "Proyectos de inversiones productivas en Cataluña 2026",
        "official_url": "https://www.accio.gencat.cat/ca/serveis/cercador-ajuts-empresa/ajutsiserveis/25140-dgi-inversions-productives",
        "territory": "Cataluña",
        "call_status": "CLOSED",
        "opening_date": "2026-03-10",
        "closing_date": "2026-04-22",
        "beneficiaries": ["Empresas industriales con actividad productiva en Cataluña"],
        "technologies": ["industrial equipment", "automation", "industry 4.0", "industrial software"],
        "budget_min_eur": 100000,
        "grant_rate_pct": 20,
        "funding_rate_pct": 20,
        "max_aid_eur": 500000,
        "aid_types": ["Grant"],
        "liquidity_notes": "At least 50% of project financing must be secured; machinery must represent at least 60% of cost.",
        "eligible_costs": ["Maquinaria", "Equipamiento productivo", "Ingeniería y software vinculados a maquinaria", "Instalaciones y obra civil"],
        "required_documents": ["Memoria de inversión", "Plan de financiación", "Ofertas y presupuesto", "Acreditación industrial, fiscal y laboral"],
        "official_verified": True,
        "verification_date": "2026-08-18",
    },
    {
        "id": "cdti-pid-open",
        "funding_id": "CDTI-PID",
        "organisation": "CDTI",
        "program": "Proyectos de I+D",
        "call_name": "Proyectos CDTI de I+D",
        "official_url": "https://www.cdti.es/ayudas/proyectos-de-i-d",
        "territory": "Spain",
        "call_status": "OPEN_CONTINUOUS",
        "beneficiaries": ["Empresas"],
        "technologies": ["ai", "robotics", "industrial software", "automation", "industrial equipment"],
        "budget_min_eur": 175000,
        "loan_rate_pct": 85,
        "funding_rate_pct": 85,
        "non_repayable_rate_pct": 10,
        "advance_rate_pct": 50,
        "advance_requires_guarantee": False,
        "payment_timing": "Advance up to 50% of aid; remainder through project milestones and justification",
        "interest_description": "Fixed rate equal to 1-year Euribor at approval",
        "repayment_years": 10,
        "grace_years": 2,
        "collateral_description": "No additional guarantee for standard advance; CDTI may require guarantees after financial risk analysis",
        "liquidity_notes": "Official options are 10 or 15 years with 2-3 years grace; conservative values shown in numeric fields.",
        "aid_types": ["Partially repayable aid", "Loan", "Non-repayable tranche"],
        "eligible_costs": ["Personal", "Instrumental y material", "Investigación contractual", "Conocimientos y patentes", "Consultoría", "Gastos generales", "Auditoría y DNSH"],
        "required_documents": ["Memoria técnica y plan de trabajo", "Presupuesto por partidas", "Plan de explotación", "Cuentas anuales y previsiones financieras", "Declaraciones de ayudas e incompatibilidades", "Documentación societaria"],
        "incentive_effect_required": True,
        "official_verified": True,
        "verification_date": "2026-08-18",
    },
)