"""Data model for intelligence outputs generated by the pipeline."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass
class IntelligenceOutput:
    output_type: str           # "pricing_alert" | "competitor_movement" | "market_trend" | "sales_opportunity"
    title: str
    description: str
    impact: str                # "high" | "medium" | "low"
    suggested_action: str
    source_url: str
    source_id: str
    created_at: datetime
    payload: dict[str, Any] = field(default_factory=dict)
