"""
Script to apply Smart Plant dashboard updates (V2).

This script writes `pages/smart_plant_dashboard_v2.py` and ensures a default
`data/smart_plant_config.json` exists. Run from repository root:

    python implementar_smart_plant_v2.py

"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PAGES = ROOT / "pages"
DATA_JSON = ROOT / "data" / "smart_plant_config.json"
DASH_PATH = PAGES / "smart_plant_dashboard_v2.py"

# The new dashboard page content (kept self-contained and simple)
DASHBOARD_CODE = r'''"""
INGECART Smart Corrugated Plant Dashboard V2

Generated by implementar_smart_plant_v2.py
"""

import streamlit as st
import json
import base64
from pathlib import Path

st.set_page_config(page_title="INGECART Smart Plant Dashboard V2", page_icon="🏭", layout="wide")

CONFIG_PATH = Path("data/smart_plant_config.json")


def load_config():
    default = {
        "overview_text": "INGECART Smart Corrugated Plant — configure aquí el texto overview.",
        "general_video_path": "assets/videos/general/overview.mp4",
        "plant_image_path": "assets/images/smart_plant_overview.png",
        "hotspots": [],
        "kpis": {"productivity": 67, "automation": 82, "labor": 34, "waste": 12},
        "subpages": [],
        "solutions_mapping": {},
        "video_url": "https://senarzuniga.github.io/ingesite.github.io/public/videos/",
    }
    if CONFIG_PATH.exists():
        try:
            c = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
        except Exception:
            c = default
        for k, v in default.items():
            if k not in c:
                c[k] = v

        # Normalize hotspots
        hotspots = c.get("hotspots", []) or []
        normalized = []
        seen_ids = set()
        for i, h in enumerate(hotspots):
            if not isinstance(h, dict):
                continue
            hid = h.get("id") or f"hotspot_{i+1}"
            if hid in seen_ids:
                hid = f"{hid}_{i+1}"
            seen_ids.add(hid)
            name = h.get("name") or hid
            try:
                x = int(float(h.get("x", 50)))
            except Exception:
                x = 50
            try:
                y = int(float(h.get("y", 50)))
            except Exception:
                y = 50
            x = max(0, min(100, x))
            y = max(0, min(100, y))

            normalized.append(
                {
                    "id": hid,
                    "name": name,
                    "x": x,
                    "y": y,
                    "description": h.get("description", ""),
                    "video": h.get("video", ""),
                    "roi": h.get("roi", ""),
                    "savings": h.get("savings", ""),
                    "image": h.get("image", ""),
                }
            )
        c["hotspots"] = normalized
        return c
    else:
        CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
        CONFIG_PATH.write_text(json.dumps(default, ensure_ascii=False, indent=2), encoding="utf-8")
        return default


# Mapping to local product images (user may edit these paths)
product_images = {
    "SR1400": r"C:\Users\Inaki Senar\Documents\INGECART\MARKETING\ARTWORK\Ingecart SR-1400 Waste System.png",
    "INGETRANS": r"C:\Users\Inaki Senar\Documents\INGECART\MARKETING\ARTWORK\Ingetrans.png",
    "AMR-C": r"C:\Users\Inaki Senar\Documents\INGECART\MARKETING\ARTWORK\INTRALOGISTICS AMR.png",
    "AMR-W": r"C:\Users\Inaki Senar\Documents\INGECART\MARKETING\ARTWORK\WIP EFFICIENCY  AMR 2.png",
    "EASYPACK": r"C:\Users\Inaki Senar\Documents\INGECART\MARKETING\ARTWORK\EASY PACK.png",
    "PALLETIZER-PP": r"C:\Users\Inaki Senar\Documents\INGECART\MARKETING\ARTWORK\Plug and Play Palletizer.png",
    "PALLETIZER-HC": r"C:\Users\Inaki Senar\Documents\INGECART\MARKETING\ARTWORK\HC_PALLETIZER.png",
    "SHIPPING": r"C:\Users\Inaki Senar\Documents\INGECART\MARKETING\ARTWORK\TRUCK LOADER.avif",
}


def get_product_overview(product_name: str) -> str:
    """Search local marketing folders for a short overview text for the product."""
    # 1. Search user's MARKETING/CONTENT folder
    content_dir = Path(r"C:\Users\Inaki Senar\Documents\INGECART\MARKETING\CONTENT")
    if content_dir.exists():
        for f in content_dir.glob(f"*{product_name}*"):
            if f.suffix.lower() in (".txt", ".md", ".rst"):
                try:
                    return f.read_text(encoding="utf-8").strip()[:800]
                except Exception:
                    pass

    # 2. Search ingecart-marketing-kit inside the repo (if present)
    kit_dir = Path("ingecart-marketing-kit")
    if kit_dir.exists():
        for f in kit_dir.rglob(f"*{product_name}*"):
            if f.suffix.lower() in (".txt", ".md", ".rst"):
                try:
                    return f.read_text(encoding="utf-8").strip()[:800]
                except Exception:
                    pass

    # 3. Fallback: use description from hotspots config
    cfg = load_config()
    for h in cfg.get("hotspots", []):
        if h.get("name") == product_name or h.get("id") == product_name:
            return h.get("description", f"Soluciones {product_name} disponibles. Consulte más información.")

    return f"Tecnología {product_name} para optimizar su planta de cartón corrugado."


def image_to_base64(path: str) -> str | None:
    p = Path(path)
    if p.exists():
        return base64.b64encode(p.read_bytes()).decode()
    return None


def render_header():
    cols = st.columns([1, 6, 1])
    with cols[1]:
        st.markdown(
            "<div style='text-align:center'>"
            "<h1 style='color:#E84C22;margin:0'>INGECART</h1>"
            "<h3 style='color:#8892b0;margin:0'>Smart Corrugated Plant</h3>"
            "</div>",
            unsafe_allow_html=True,
        )


def render_filters(config: dict) -> None:
    filters = [
        "All",
        "Labor shortage",
        "Productivity",
        "Waste",
        "Logistics",
        "Sustainability",
        "Energy",
    ]
    cols = st.columns(len(filters))
    for i, f in enumerate(filters):
        with cols[i]:
            if st.button(f, key=f"filter_{f}", use_container_width=True):
                st.session_state.active_filter = f
                st.experimental_rerun()


def render_plant(config: dict, highlight_ids=None) -> None:
    plant_img_b64 = image_to_base64(config.get("plant_image_path", ""))
    img_src = f"data:image/png;base64,{plant_img_b64}" if plant_img_b64 else ""

    html = f"""
    <div style="position:relative;width:100%;border-radius:8px;overflow:hidden;background:#0a0e1a;padding:6px;">
      <img src=\"{img_src}\" style=\"width:100%; display:block; border-radius:6px;\" />
      <div id=\"hotspots\" style=\"position:absolute;left:0;top:0;width:100%;height:100%;\">\n
    """

    for h in config.get("hotspots", []):
        is_high = (highlight_ids is None) or (h.get("id") in (highlight_ids or []))
        opacity = "1" if is_high else "0.25"
        left = f"{h.get('x', 50)}%"
        top = f"{h.get('y', 50)}%"
        name = h.get("name", "")
        hid = h.get("id")
        html += f"""
        <div class=\"hotspot-hexagon\" title=\"{name}\" onclick=\"(function(){{try{{Streamlit.setComponentValue('{hid}');}}catch(e){{window.parent.postMessage({{'hotspot':'{hid}'}}, '*');}}}})()\"
             style=\"position:absolute;left:{left};top:{top};transform:translate(-50%,-50%);width:36px;height:36px;\
                background:rgba(232,76,34,{opacity});border-radius:50%;cursor:pointer;box-shadow:0 6px 18px rgba(0,0,0,0.4);\
                display:flex;align-items:center;justify-content:center;color:white;font-weight:bold;\">
          <span style=\"font-size:12px;\">●</span>
        </div>\n
        """

    html += "</div></div>"

    import streamlit.components.v1 as components
    try:
        clicked = components.html(html, height=560, scrolling=False)
    except Exception:
        try:
            st.iframe(html, height=560)
        except Exception:
            st.write("[Error rendering plant view]")
        clicked = None

    return clicked


def render_right_panel(config: dict, selected_hotspot_id: str = None) -> None:
    # Removed global plant status; focus on overview and selected hotspot
    st.markdown("### 🎥 OVERVIEW VIDEO")
    vpath = config.get("general_video_path", "")
    if Path(vpath).exists():
        st.video(str(vpath))
    else:
        st.info("Sube el video general en el configurador (assets/videos/general/overview.mp4)")

    st.markdown("---")
    st.markdown("### 📋 OVERVIEW")
    st.write(config.get("overview_text", ""))

    if selected_hotspot_id:
        st.markdown("---")
        hotspot = next((h for h in config.get("hotspots", []) if h.get("id") == selected_hotspot_id), None)
        if hotspot:
            st.markdown(f"### 🔧 {hotspot.get('name')}")
            # product image from mapping or hotspot config
            img_path = product_images.get(hotspot.get('name')) or hotspot.get('image')
            if img_path and Path(img_path).exists():
                st.image(str(img_path), use_column_width=True, caption=hotspot.get('name'))

            overview = get_product_overview(hotspot.get('name'))
            st.write(overview)

            # video for the hotspot if provided
            if hotspot.get('video') and Path(hotspot.get('video')).exists():
                st.video(str(hotspot.get('video')))
            else:
                video_url = config.get('video_url', '')
                if video_url:
                    st.markdown(f"[▶ Ver video de la solución]({video_url})", unsafe_allow_html=True)

            st.download_button("📥 Brochure (placeholder)", data="PDF", file_name=f"{hotspot.get('id')}_brochure.pdf")
            if st.button("Enviar detalle al chat"):
                st.session_state.chat = st.session_state.get("chat", [])
                st.session_state.chat.append(f"{hotspot.get('name')}: {hotspot.get('description')}")
                st.experimental_rerun()


def render_chat_area() -> None:
    st.markdown("### 💬 Chat demo")
    chat = st.session_state.get("chat", [])
    for msg in chat:
        st.write(msg)


def get_query_params_compat() -> dict:
    for name in ("get_query_params", "experimental_get_query_params"):
        fn = getattr(st, name, None)
        if callable(fn):
            try:
                return fn()
            except Exception:
                continue
    return {}


def set_query_params_compat(params: dict) -> None:
    fn = getattr(st, "experimental_set_query_params", None)
    if callable(fn):
        try:
            fn(**params)
            return
        except Exception:
            pass
    fn2 = getattr(st, "set_query_params", None)
    if callable(fn2):
        try:
            fn2(**params)
        except Exception:
            pass


def main():
    if "active_filter" not in st.session_state:
        st.session_state.active_filter = "All"
    if "chat" not in st.session_state:
        st.session_state.chat = []
    config = load_config()

    # Inject minimal CSS for hexagons
    css = """
    .hotspot-hexagon { position: absolute; width: 36px; height: 36px; border-radius: 50%; display:flex; align-items:center; justify-content:center; }
    .hotspot-hexagon span { font-size:12px }
    """
    st.markdown(f"<style>{css}</style>", unsafe_allow_html=True)

    render_header()
    render_filters(config)
    active_filter = st.session_state.get("active_filter", "All")
    mapping = config.get("solutions_mapping", {})
    highlight_ids = None if active_filter == "All" else mapping.get(active_filter, [])

    c1, c2 = st.columns([2, 1])
    clicked = None
    with c1:
        clicked = render_plant(config, highlight_ids=highlight_ids)

    if clicked:
        try:
            if isinstance(clicked, dict) and "hotspot" in clicked:
                hid = clicked.get("hotspot")
            else:
                hid = str(clicked)
            st.session_state["selected_hotspot"] = hid
            set_query_params_compat({"hotspot": hid})
            try:
                st.experimental_rerun()
            except Exception:
                pass
        except Exception:
            pass

    with c2:
        params = get_query_params_compat()
        hotspot_id = st.session_state.get("selected_hotspot") or params.get("hotspot", [None])[0]
        render_right_panel(config, selected_hotspot_id=hotspot_id)
        render_chat_area()


if __name__ == "__main__":
    main()
'''


def main():
    PAGES.mkdir(parents=True, exist_ok=True)
    DASH_PATH.write_text(DASHBOARD_CODE, encoding="utf-8")
    print(f"Wrote {DASH_PATH}")

    DATA_JSON.parent.mkdir(parents=True, exist_ok=True)
    if not DATA_JSON.exists():
        default_config = {
            "overview_text": "Planta de cartón corrugado totalmente automatizada. Haga clic en cualquier hexágono para conocer la solución asociada.",
            "plant_image_path": "",
            "hotspots": [
                {"id": "SR1400", "name": "SR1400", "x": 10, "y": 10, "description": "", "roi": "", "savings": "", "video": "", "image": ""},
                {"id": "INGETRANS", "name": "INGETRANS", "x": 30, "y": 20, "description": "", "roi": "", "savings": "", "video": "", "image": ""},
            ],
            "kpis": {"productivity": 92, "automation": 87, "labor": 42, "waste": 6},
            "video_url": "https://senarzuniga.github.io/ingesite.github.io/public/videos/",
        }
        DATA_JSON.write_text(json.dumps(default_config, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"Created {DATA_JSON}")


if __name__ == "__main__":
    main()
