"""Python-side discrete-event simulation engine for the Corrugated Plant Simulator.

Runs a time-step simulation (dt=1 s) and produces analytics:
  - Throughput, OEE, utilization, bottleneck detection
  - Per-minute timeline snapshots
  - Multi-scenario comparison (for optimization)
"""
from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from .models import (
    BottleneckRecord,
    MachineMetric,
    PlantConfig,
    PlantType,
    SimulationResults,
    TransportType,
)

# ---------------------------------------------------------------------------
# Internal simulation state objects
# ---------------------------------------------------------------------------

@dataclass
class _MachineState:
    id: str
    capacity_per_hour: float       # units or m² per hour (theoretical max)
    availability: float = 0.92     # scheduled availability
    speed_loss: float = 0.95       # performance ratio
    quality: float = 0.99          # quality ratio
    # Runtime
    state: str = "running"         # running, blocked, setup, maintenance, idle
    produced: float = 0.0
    blocked_seconds: float = 0.0
    setup_seconds: float = 0.0
    maintenance_seconds: float = 0.0
    running_seconds: float = 0.0
    queue_in: float = 0.0          # units waiting upstream
    queue_out: float = 0.0         # units waiting downstream
    queue_in_max: float = 0.0
    setup_timer: float = 0.0       # seconds until setup finishes

    @property
    def oee(self) -> float:
        return self.availability * self.speed_loss * self.quality

    @property
    def actual_rate_per_hour(self) -> float:
        return self.capacity_per_hour * self.oee


@dataclass
class _StorageState:
    id: str
    capacity: float
    current: float = 0.0
    inflow_total: float = 0.0
    outflow_total: float = 0.0

    @property
    def occupancy(self) -> float:
        return self.current / max(self.capacity, 1)

    def add(self, amount: float) -> float:
        """Add to storage, returns actual amount added."""
        space = self.capacity - self.current
        added = min(amount, max(space, 0))
        self.current += added
        self.inflow_total += added
        return added

    def remove(self, amount: float) -> float:
        """Remove from storage, returns actual amount removed."""
        removed = min(amount, max(self.current, 0))
        self.current -= removed
        self.outflow_total += removed
        return removed


@dataclass
class _TransportState:
    num_vehicles: int = 3
    speed_ms: float = 1.5          # m/s
    trip_distance_m: float = 30.0  # avg trip distance
    load_time_s: float = 60.0      # load + unload time
    active_trips: int = 0
    total_trips: int = 0
    idle_seconds: float = 0.0
    active_seconds: float = 0.0

    @property
    def cycle_time_s(self) -> float:
        """One-way trip time in seconds."""
        return self.trip_distance_m / max(self.speed_ms, 0.1) + self.load_time_s

    @property
    def utilization(self) -> float:
        total = max(self.idle_seconds + self.active_seconds, 1)
        return self.active_seconds / total


# ---------------------------------------------------------------------------
# Simulation engine
# ---------------------------------------------------------------------------

class SimulationEngine:
    """
    Run a discrete time-step simulation of a corrugated plant.

    Parameters
    ----------
    config : PlantConfig
        Plant configuration generated by ConfigAgent.
    dt : float
        Time step in seconds (default 1 s).
    seed : int
        Random seed for reproducibility.
    """

    DT = 1.0  # simulation time step (seconds)
    MAINTENANCE_PROB = 0.0002   # probability per second of unplanned stop
    MAINTENANCE_DURATION = 600  # seconds (10 min avg)
    SETUP_DURATION = 1800       # seconds (30 min changeover)
    SETUP_INTERVAL = 14400      # seconds between setups (4 hours)

    def __init__(self, config: PlantConfig, seed: int = 42):
        self.config = config
        self.rng = random.Random(seed)
        self._machines: List[_MachineState] = []
        self._storages: Dict[str, _StorageState] = {}
        self._transport: Optional[_TransportState] = None
        self._timeline: List[Dict[str, Any]] = []
        self._bottleneck_counters: Dict[str, int] = {}
        self._setup_timer_map: Dict[str, float] = {}  # machine_id -> next setup at

    # ------------------------------------------------------------------ #
    # Public API                                                            #
    # ------------------------------------------------------------------ #

    def run(self, progress_callback=None) -> SimulationResults:
        """Run the full simulation and return results."""
        self._initialize()
        total_steps = int(self.config.simulation_duration_hours * 3600 / self.DT)
        snapshot_interval = 60  # every 60 simulated seconds

        for step in range(total_steps):
            self._tick(step * self.DT)

            if step % snapshot_interval == 0 and step > 0:
                self._timeline.append(self._snapshot(step * self.DT))

            if progress_callback and step % (total_steps // 20) == 0:
                progress_callback(step / total_steps)

        return self._build_results()

    def run_scenario(
        self,
        overrides: Dict[str, Any],
        label: str = "Escenario",
    ) -> SimulationResults:
        """Run with parameter overrides for scenario comparison."""
        import copy
        cfg = copy.deepcopy(self.config)
        # Apply overrides to config
        for key, val in overrides.items():
            if hasattr(cfg, key):
                setattr(cfg, key, val)
            elif cfg.corrugator and hasattr(cfg.corrugator, key):
                setattr(cfg.corrugator, key, val)
            elif cfg.transport and hasattr(cfg.transport, key):
                setattr(cfg.transport, key, val)
        engine = SimulationEngine(cfg, seed=self.rng.randint(0, 9999))
        result = engine.run()
        result.scenario_label = label
        return result

    # ------------------------------------------------------------------ #
    # Initialization                                                        #
    # ------------------------------------------------------------------ #

    def _initialize(self) -> None:
        cfg = self.config
        self._machines = []
        self._storages = {}

        # Corrugator
        if cfg.plant_type in (PlantType.CORRUGATOR_CONVERTER, PlantType.CORRUGATOR_ONLY):
            corr = cfg.corrugator
            m2_per_h = corr.m2_per_hour if corr else 15000
            self._machines.append(
                _MachineState(
                    id="corrugadora",
                    capacity_per_hour=m2_per_h,
                    availability=0.92,
                    speed_loss=0.95,
                    quality=0.99,
                )
            )
            self._storages["roll_store"] = _StorageState(
                "roll_store",
                capacity=corr.roll_store_capacity if corr else 100,
                current=corr.roll_store_capacity * 0.8 if corr else 80,
            )
            self._storages["buffer"] = _StorageState(
                "buffer",
                capacity=cfg.storage.buffer_capacity_pallets,
                current=0,
            )
        elif cfg.plant_type == PlantType.CONVERTER_ONLY:
            self._storages["input_store"] = _StorageState(
                "input_store",
                capacity=cfg.storage.input_capacity_pallets,
                current=cfg.storage.input_capacity_pallets * 0.7,
            )
            self._storages["buffer"] = _StorageState(
                "buffer",
                capacity=cfg.storage.buffer_capacity_pallets,
                current=int(cfg.storage.buffer_capacity_pallets * 0.5),
            )

        # Converters
        for cv in cfg.converters:
            self._machines.append(
                _MachineState(
                    id=cv.id,
                    capacity_per_hour=cv.speed_units_per_hour,
                    availability=cv.availability,
                    speed_loss=0.93,
                    quality=0.98,
                )
            )
            self._setup_timer_map[cv.id] = self.SETUP_INTERVAL + self.rng.uniform(0, 3600)

        # Output storage
        self._storages["output"] = _StorageState(
            "output",
            capacity=cfg.storage.output_capacity_pallets,
            current=0,
        )

        # Transport
        self._transport = _TransportState(
            num_vehicles=cfg.transport.num_forklifts,
            speed_ms=cfg.transport.forklift_speed_ms,
        )
        if cfg.transport.type == TransportType.TRACKS:
            self._transport.speed_ms = 0.8
            self._transport.trip_distance_m = 20.0
            self._transport.load_time_s = 20.0
        elif cfg.transport.type == TransportType.CONVEYORS:
            self._transport.speed_ms = 0.5
            self._transport.trip_distance_m = 15.0
            self._transport.load_time_s = 5.0

        self._timeline = []
        self._bottleneck_counters = {}

    # ------------------------------------------------------------------ #
    # Tick logic                                                            #
    # ------------------------------------------------------------------ #

    def _tick(self, sim_time: float) -> None:
        dt = self.DT
        cfg = self.config
        has_corrugator = cfg.plant_type in (PlantType.CORRUGATOR_CONVERTER, PlantType.CORRUGATOR_ONLY)

        # 1. Roll store replenishment (external supply always present)
        if "roll_store" in self._storages:
            rs = self._storages["roll_store"]
            if rs.current < rs.capacity * 0.4:
                rs.add(rs.capacity * 0.3)  # truck delivery

        # 2. Update machines
        for m in self._machines:
            self._update_machine(m, sim_time, dt)

        # 3. Flow from corrugator → buffer
        if has_corrugator and "buffer" in self._storages:
            corr = self._get_machine("corrugadora")
            buf = self._storages["buffer"]
            if corr and corr.state == "running":
                m2_produced = corr.actual_rate_per_hour * dt / 3600
                # Convert m² to pallets (approx 200 m² per pallet of plano)
                pallets_produced = m2_produced / 200.0
                added = buf.add(pallets_produced)
                corr.produced += m2_produced
                if added < pallets_produced * 0.9:
                    # Buffer nearly full → corrugator blocked
                    corr.state = "blocked"
                    corr.blocked_seconds += dt
                    self._count_bottleneck("buffer_full")
            elif corr and corr.state == "blocked":
                # Check if buffer freed up
                if buf.occupancy < 0.85:
                    corr.state = "running"

        # 4. Flow from input_store → buffer (converter_only)
        if "input_store" in self._storages and "buffer" in self._storages:
            inp = self._storages["input_store"]
            buf = self._storages["buffer"]
            demand = max(0, buf.capacity * 0.5 - buf.current)
            amount = min(demand, inp.current, dt * 2)  # ~2 pallets/s max supply
            removed = inp.remove(amount)
            buf.add(removed)

        # 5. Flow from buffer → converters → output
        if "buffer" in self._storages:
            buf = self._storages["buffer"]
            output = self._storages.get("output")
            converters = [m for m in self._machines if m.id.startswith("C")]
            for cv in converters:
                if cv.state == "running":
                    pallets_needed = cv.actual_rate_per_hour * dt / 3600 / 50  # ~50 units per pallet
                    removed = buf.remove(pallets_needed)
                    cv.produced += removed * 50  # back to units
                    if output:
                        output.add(removed * 0.98)  # 2% scrap
                    if removed < pallets_needed * 0.5:
                        self._count_bottleneck(f"starvation_{cv.id}")
                elif cv.state == "blocked":
                    if output and output.occupancy < 0.85:
                        cv.state = "running"

        # 6. Transport dynamics
        if self._transport:
            self._update_transport(dt, sim_time)

        # 7. Output expedicion (truck pickup every ~30 min)
        if "output" in self._storages:
            out = self._storages["output"]
            if sim_time % 1800 < dt:  # every 30 min
                out.remove(out.capacity * 0.3)

    def _update_machine(self, m: _MachineState, sim_time: float, dt: float) -> None:
        """Apply stochastic events (maintenance, setup) and track time."""
        if m.state == "maintenance":
            m.maintenance_seconds += dt
            m.setup_timer -= dt
            if m.setup_timer <= 0:
                m.state = "running"
            return

        if m.state == "setup":
            m.setup_seconds += dt
            m.setup_timer -= dt
            if m.setup_timer <= 0:
                m.state = "running"
                self._setup_timer_map[m.id] = sim_time + self.SETUP_INTERVAL
            return

        if m.state == "running":
            m.running_seconds += dt

            # Unplanned maintenance
            if self.rng.random() < self.MAINTENANCE_PROB * dt:
                m.state = "maintenance"
                m.setup_timer = self.rng.uniform(
                    self.MAINTENANCE_DURATION * 0.5,
                    self.MAINTENANCE_DURATION * 1.5,
                )
                return

            # Planned changeover
            if m.id in self._setup_timer_map and sim_time >= self._setup_timer_map.get(m.id, float("inf")):
                if m.id.startswith("C"):  # converters only
                    m.state = "setup"
                    m.setup_timer = self.SETUP_DURATION
                    return

    def _update_transport(self, dt: float, sim_time: float) -> None:
        tr = self._transport
        if tr is None:
            return
        cycle = tr.cycle_time_s
        trips_per_second = tr.num_vehicles / cycle
        tr.total_trips += trips_per_second * dt
        # Utilization: depends on queue demand
        buf_occ = self._storages.get("buffer", _StorageState("x", 1, 0)).occupancy
        demand = min(buf_occ * 1.5, 1.0)
        active_frac = min(demand * 1.2, 1.0)
        tr.active_seconds += dt * active_frac * tr.num_vehicles
        tr.idle_seconds += dt * (1 - active_frac) * tr.num_vehicles

    # ------------------------------------------------------------------ #
    # Helpers                                                               #
    # ------------------------------------------------------------------ #

    def _get_machine(self, machine_id: str) -> Optional[_MachineState]:
        for m in self._machines:
            if m.id == machine_id:
                return m
        return None

    def _count_bottleneck(self, key: str) -> None:
        self._bottleneck_counters[key] = self._bottleneck_counters.get(key, 0) + 1

    def _snapshot(self, sim_time: float) -> Dict[str, Any]:
        snap: Dict[str, Any] = {
            "time_s": sim_time,
            "time_min": round(sim_time / 60, 1),
        }
        for m in self._machines:
            snap[f"{m.id}_produced"] = round(m.produced, 1)
            snap[f"{m.id}_oee"] = round(m.oee * 100, 1)
            snap[f"{m.id}_blocked_pct"] = round(
                m.blocked_seconds / max(m.running_seconds + m.blocked_seconds, 1) * 100, 1
            )
        for sid, st in self._storages.items():
            snap[f"{sid}_occupancy_pct"] = round(st.occupancy * 100, 1)
        if self._transport:
            snap["transport_utilization_pct"] = round(self._transport.utilization * 100, 1)
        return snap

    # ------------------------------------------------------------------ #
    # Results compilation                                                   #
    # ------------------------------------------------------------------ #

    def _build_results(self) -> SimulationResults:
        cfg = self.config

        # Machine metrics
        machine_metrics = []
        for m in self._machines:
            total_s = m.running_seconds + m.blocked_seconds + m.setup_seconds + m.maintenance_seconds
            avail = (m.running_seconds + m.blocked_seconds) / max(total_s, 1)
            perf = m.speed_loss if m.running_seconds > 0 else 0
            qual = m.quality
            oee = avail * perf * qual
            machine_metrics.append(
                MachineMetric(
                    machine_id=m.id,
                    availability=round(avail * 100, 1),
                    performance=round(perf * 100, 1),
                    quality=round(qual * 100, 1),
                    oee=round(oee * 100, 1),
                    units_produced=round(m.produced, 0),
                    blocked_time_s=round(m.blocked_seconds, 0),
                    setup_time_s=round(m.setup_seconds, 0),
                )
            )

        # Bottlenecks
        bottlenecks = []
        for key, count in self._bottleneck_counters.items():
            if count > 30:  # only significant
                avg_wait = min(count * self.DT / 60, 300)  # seconds
                bottlenecks.append(
                    BottleneckRecord(
                        location=key,
                        type="machine" if key.startswith("starvation") else "storage",
                        avg_wait_s=round(avg_wait, 1),
                        max_wait_s=round(avg_wait * 2.5, 1),
                        frequency=count,
                    )
                )
        bottlenecks.sort(key=lambda b: b.avg_wait_s, reverse=True)

        # KPIs
        corr = self._get_machine("corrugadora")
        m2_total = corr.produced if corr else 0
        units_total = sum(
            m.produced for m in self._machines if m.id.startswith("C")
        )
        corr_eff = (corr.oee * 100) if corr else 0
        avg_oee = (
            sum(m.oee for m in self._machines) / max(len(self._machines), 1) * 100
        )
        buf = self._storages.get("buffer")
        buf_max = 0.0
        buf_avg = 0.0
        if self._timeline:
            occ_vals = [s.get("buffer_occupancy_pct", 0) for s in self._timeline]
            buf_max = max(occ_vals) if occ_vals else 0
            buf_avg = sum(occ_vals) / len(occ_vals) if occ_vals else 0

        transport_util = (
            self._transport.utilization * 100 if self._transport else 0
        )

        # Auto-recommendations
        recommendations = self._generate_recommendations(
            bottlenecks, machine_metrics, buf_avg, transport_util
        )

        return SimulationResults(
            sim_id=cfg.id,
            plant_name=cfg.name,
            plant_type=cfg.plant_type.value,
            duration_hours=cfg.simulation_duration_hours,
            m2_produced=round(m2_total, 0),
            total_units_converted=round(units_total, 0),
            corrugator_efficiency=round(corr_eff, 1),
            average_oee=round(avg_oee, 1),
            transport_utilization=round(transport_util, 1),
            buffer_max_occupancy=round(buf_max, 1),
            buffer_avg_occupancy=round(buf_avg, 1),
            machine_metrics=machine_metrics,
            bottlenecks=bottlenecks,
            timeline=self._timeline,
            recommendations=recommendations,
        )

    def _generate_recommendations(
        self,
        bottlenecks: List[BottleneckRecord],
        metrics: List[MachineMetric],
        buf_avg: float,
        transport_util: float,
    ) -> List[str]:
        recs = []

        # Buffer congestion
        if buf_avg > 75:
            recs.append(
                "📦 **Buffer congestionado** (ocupación media {:.0f}%): ampliar capacidad de almacén "
                "intermedio o añadir una línea de conversión para absorber el flujo.".format(buf_avg)
            )

        # Buffer starvation
        if buf_avg < 25:
            recs.append(
                "⚠️ **Buffer infrautilizado** (ocupación media {:.0f}%): la corrugadora produce menos "
                "de lo que las convertidoras demandan. Revisar velocidad de corrugadora o "
                "programación de pedidos.".format(buf_avg)
            )

        # Machine OEE below benchmark
        for m in metrics:
            if m.oee < 75:
                recs.append(
                    f"⚙️ **OEE bajo en {m.machine_id}** ({m.oee:.1f}%): implementar TPM focalizando "
                    "en reducción de paradas no planificadas y tiempos de cambio de orden."
                )

        # High blocked time (corrugator)
        for m in metrics:
            if m.machine_id == "corrugadora" and m.blocked_time_s > 1800:
                recs.append(
                    "🏭 **Corrugadora bloqueada** {:.0f} min/turno: el buffer de salida se llena antes "
                    "de que conversión lo vacíe. Aumentar velocidad de conversión o reducir "
                    "velocidad de corrugadora.".format(m.blocked_time_s / 60)
                )

        # High transport utilization
        if transport_util > 85:
            recs.append(
                "🚛 **Transporte saturado** ({:.0f}% utilización): añadir 1-2 carretillas o "
                "automatizar el tramo con tracks guiados para eliminar esperas.".format(transport_util)
            )

        # Top bottlenecks
        for bt in bottlenecks[:2]:
            recs.append(
                f"🔴 **Cuello de botella en {bt.location}**: espera media {bt.avg_wait_s:.0f}s, "
                "detectado {bt.frequency} veces. Acción: revisar ritmo upstream/downstream."
            )

        if not recs:
            recs.append(
                "✅ **Planta bien equilibrada.** El flujo productivo es estable con los parámetros "
                "actuales. OEE medio por encima de referencia sectorial (78%)."
            )

        return recs


# ---------------------------------------------------------------------------
# Multi-scenario optimizer
# ---------------------------------------------------------------------------

class ScenarioOptimizer:
    """Run multiple scenarios and compare results."""

    BASE_SCENARIOS = [
        {
            "label": "Base",
            "description": "Configuración actual sin cambios",
            "overrides": {},
        },
        {
            "label": "+1 Carretilla",
            "description": "Añadir 1 carretilla al transporte interno",
            "overrides_transport": {"num_forklifts_delta": 1},
        },
        {
            "label": "+1 Convertidora",
            "description": "Añadir una línea de conversión idéntica",
            "overrides_config": "add_converter",
        },
        {
            "label": "Tracks (automático)",
            "description": "Reemplazar carretillas por tracks guiados",
            "overrides_transport": {"type": "tracks", "num_forklifts": 2},
        },
        {
            "label": "Buffer +50%",
            "description": "Ampliar almacén intermedio un 50%",
            "overrides_storage": {"buffer_delta_pct": 0.5},
        },
    ]

    def run_all(
        self, config: PlantConfig, progress_callback=None
    ) -> List[SimulationResults]:
        import copy
        results = []

        for i, scenario in enumerate(self.BASE_SCENARIOS):
            cfg = copy.deepcopy(config)
            label = scenario["label"]

            # Apply overrides
            if "overrides_transport" in scenario:
                ov = scenario["overrides_transport"]
                if "num_forklifts_delta" in ov:
                    cfg.transport.num_forklifts += ov["num_forklifts_delta"]
                if "type" in ov:
                    from .models import TransportType
                    cfg.transport.type = TransportType(ov["type"])
                if "num_forklifts" in ov:
                    cfg.transport.num_forklifts = ov["num_forklifts"]
            if scenario.get("overrides_config") == "add_converter" and cfg.converters:
                import copy as cp2
                new_cv = cp2.deepcopy(cfg.converters[-1])
                new_cv.id = f"C{len(cfg.converters)+1}"
                cfg.converters.append(new_cv)
            if "overrides_storage" in scenario:
                ov = scenario["overrides_storage"]
                if "buffer_delta_pct" in ov:
                    cfg.storage.buffer_capacity_pallets = int(
                        cfg.storage.buffer_capacity_pallets * (1 + ov["buffer_delta_pct"])
                    )

            engine = SimulationEngine(cfg, seed=42)
            result = engine.run()
            result.scenario_label = label
            results.append(result)

            if progress_callback:
                progress_callback((i + 1) / len(self.BASE_SCENARIOS))

        return results
