"""Create a small demo project for the Project Closeout panel.

This script seeds a demo project and a sample punch list CSV so the UI
can be validated quickly.
"""
from __future__ import annotations

import csv
import os
from services.project_closeout_service import ProjectCloseoutService


def main():
    svc = ProjectCloseoutService()
    pid = "DEMO-001"
    svc.upsert_project(pid, {"project_name": "Demo Project 001", "customer": "ACME Corp", "description": "Demo project generated by script"})
    # create a sample punchlist
    out = os.path.join("data", "project_closeout", "demo")
    os.makedirs(out, exist_ok=True)
    csv_path = os.path.join(out, "demo_punchlist.csv")
    rows = [
        {"Issue ID": "ISS-001", "Description": "Loose bolts on conveyor", "Owner": "Luis", "Status": "Open", "Priority": "High"},
        {"Issue ID": "ISS-002", "Description": "PLC alarm on station 3", "Owner": "Ana", "Status": "In progress", "Priority": "Critical"},
    ]
    with open(csv_path, "w", newline='', encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        for r in rows:
            writer.writerow(r)

    # import into DB
    with open(csv_path, "rb") as fh:
        res = svc.import_issues_from_file(pid, fh, "demo_punchlist.csv")
    print("Demo project created:", pid, res)


if __name__ == '__main__':
    main()
