from __future__ import annotations

import html
import json
from typing import Any

from .models import PresentationAnalysis, SlideAnalysis, SlideElement


def generate_slide_flow_html(analysis: PresentationAnalysis, theme: dict[str, Any], css_href: str) -> str:
    nav = _build_nav(analysis)
    sections = "\n".join(_render_slide_section(slide, mode="flow") for slide in analysis.slides)
    summary = _build_summary(analysis)

    return f"""<!doctype html>
<html lang=\"en\" data-theme=\"light\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />
  <title>PIE Slide Flow - {html.escape(analysis.metadata.get('source_name', 'presentation'))}</title>
  <meta name=\"description\" content=\"Slide Flow HTML generated by Presentation Intelligence Engine\" />
  <link rel=\"stylesheet\" href=\"{css_href}\" />
  <style>{_shared_ui_css()}</style>
</head>
<body>
  {_sidebar_shell(nav)}
  <main>
    {_hero_block('Version 1 - Slide Flow HTML', analysis)}
    {summary}
    <div class=\"sections\" data-scroll-snap=\"on\">{sections}</div>
    {_footer(analysis)}
  </main>
  {_ai_panel()}
  {_ui_scripts()}
</body>
</html>"""


def generate_smart_reconstruction_html(analysis: PresentationAnalysis, theme: dict[str, Any], css_href: str) -> str:
    nav = _build_nav(analysis)
    sections = "\n".join(_render_slide_section(slide, mode="smart") for slide in analysis.slides)
    summary = _build_summary(analysis)

    return f"""<!doctype html>
<html lang=\"en\" data-theme=\"light\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />
  <title>PIE Smart Reconstruction - {html.escape(analysis.metadata.get('source_name', 'presentation'))}</title>
  <meta name=\"description\" content=\"Smart HTML Reconstruction generated by Presentation Intelligence Engine\" />
  <link rel=\"stylesheet\" href=\"{css_href}\" />
  <style>{_shared_ui_css()}</style>
</head>
<body>
  {_sidebar_shell(nav)}
  <main>
    {_hero_block('Version 2 - Smart HTML Reconstruction', analysis)}
    {summary}
    <div class=\"sections smart\">{sections}</div>
    {_footer(analysis)}
  </main>
  {_ai_panel()}
  {_ui_scripts()}
</body>
</html>"""


def _build_nav(analysis: PresentationAnalysis) -> str:
    items = []
    for slide in analysis.slides:
        title = html.escape(slide.title or f"Slide {slide.index}")
        items.append(f"<a href='#slide-{slide.index}' class='toc-item' data-target='slide-{slide.index}'>{slide.index}. {title}</a>")
    return "\n".join(items)


def _build_summary(analysis: PresentationAnalysis) -> str:
    palette = " ".join(f"<span class='chip'>{html.escape(c)}</span>" for c in analysis.global_palette[:8])
    return f"""
<section class=\"section-card\" id=\"executive-summary\">
  <h2>Executive Summary</h2>
  <p>Presentation Intelligence Engine converted <strong>{analysis.slide_count}</strong> slides into reusable HTML components with responsive behavior.</p>
  <div class=\"kpis\">
    <div class=\"kpi\"><span>Slides</span><strong>{analysis.slide_count}</strong></div>
    <div class=\"kpi\"><span>Palette Colors</span><strong>{len(analysis.global_palette)}</strong></div>
    <div class=\"kpi\"><span>Typography Families</span><strong>{len(analysis.typography.get('font_usage', {}))}</strong></div>
  </div>
  <div class=\"chips\">{palette}</div>
</section>
"""


def _render_slide_section(slide: SlideAnalysis, mode: str) -> str:
    blocks = []
    blocks.append(f"<div class='breadcrumb'>Home / Chapter {slide.index} / {html.escape(slide.title)}</div>")
    blocks.append(f"<h2>{html.escape(slide.title or f'Slide {slide.index}')}</h2>")

    if mode == "flow":
        for el in slide.elements:
            blocks.append(_render_element_flow(el))
    else:
        grouped = _group_elements_for_smart(slide.elements)
        for gname, items in grouped.items():
            blocks.append(f"<h3>{html.escape(gname)}</h3>")
            blocks.append("<div class='grid'>")
            for item in items:
                blocks.append(_render_element_smart(item))
            blocks.append("</div>")

    return f"""
<section class=\"section-card slide\" id=\"slide-{slide.index}\" data-title=\"{html.escape(slide.title)}\">
  {''.join(blocks)}
</section>
"""


def _render_element_flow(el: SlideElement) -> str:
    if el.kind in {"title", "heading", "text", "smartart"}:
        cls = "title" if el.kind == "title" else "text"
        content = _paragraphs(el.text)
        return f"<article class='element {cls}'>{content}</article>"
    if el.kind == "image" and el.asset_path:
        return f"<figure class='element image'><img src='{html.escape(el.asset_path)}' loading='lazy' alt='slide visual' /></figure>"
    if el.kind == "table":
        return _render_table(el.table_rows)
    if el.kind == "chart":
        return _render_chart_svg(el.chart)
    return ""


def _render_element_smart(el: SlideElement) -> str:
    if el.kind in {"title", "heading", "text", "smartart"}:
        return f"<article class='card'><p>{_escape_and_trim(el.text, 400)}</p></article>"
    if el.kind == "image" and el.asset_path:
        return f"<article class='card image'><img src='{html.escape(el.asset_path)}' loading='lazy' alt='component image' /></article>"
    if el.kind == "table":
        return f"<article class='card'>{_render_table(el.table_rows)}</article>"
    if el.kind == "chart":
        return f"<article class='card'>{_render_chart_svg(el.chart)}</article>"
    return ""


def _group_elements_for_smart(elements: list[SlideElement]) -> dict[str, list[SlideElement]]:
    groups = {
        "Narrative": [],
        "Cards and Lists": [],
        "Data Tables": [],
        "Charts and Diagrams": [],
        "Visual Assets": [],
    }
    for el in elements:
        if el.kind in {"title", "heading", "text"}:
            if "\n" in el.text or "- " in el.text:
                groups["Cards and Lists"].append(el)
            else:
                groups["Narrative"].append(el)
        elif el.kind == "table":
            groups["Data Tables"].append(el)
        elif el.kind in {"chart", "smartart"}:
            groups["Charts and Diagrams"].append(el)
        elif el.kind == "image":
            groups["Visual Assets"].append(el)

    return {k: v for k, v in groups.items() if v}


def _render_table(rows: list[list[str]]) -> str:
    if not rows:
        return ""
    head = rows[0]
    body = rows[1:] if len(rows) > 1 else []
    th = "".join(f"<th>{html.escape(c)}</th>" for c in head)
    tr = "".join("<tr>" + "".join(f"<td>{html.escape(c)}</td>" for c in row) + "</tr>" for row in body)
    csv_payload = json.dumps(rows)
    return f"""
<div class='table-tools'>
  <button type='button' class='btn tiny' onclick='pieSortTable(this)'>Sort</button>
  <button type='button' class='btn tiny' onclick='pieExportTable(this, {csv_payload})'>Export CSV</button>
</div>
<div class='table-wrap'><table><thead><tr>{th}</tr></thead><tbody>{tr}</tbody></table></div>
"""


def _render_chart_svg(chart: dict[str, Any]) -> str:
    series = chart.get("series") or []
    if not series or not isinstance(series, list):
        return "<div class='chart-empty'>Chart metadata detected but values were not available.</div>"

    values = [float(v or 0) for v in series[0].get("values", [])]
    if not values:
        return "<div class='chart-empty'>Chart values unavailable.</div>"

    max_val = max(values) or 1.0
    bars = []
    width = 520
    height = 220
    pad = 24
    bw = max((width - pad * 2) / max(len(values), 1) - 8, 8)
    for idx, val in enumerate(values):
        x = pad + idx * (bw + 8)
        h = int((val / max_val) * (height - 60))
        y = height - h - 20
        bars.append(f"<rect x='{x:.1f}' y='{y}' width='{bw:.1f}' height='{h}' rx='4'></rect>")

    return f"""
<svg class='chart' viewBox='0 0 {width} {height}' role='img' aria-label='Reconstructed chart'>
  <line x1='20' y1='{height-20}' x2='{width-20}' y2='{height-20}'></line>
  {''.join(bars)}
</svg>
"""


def _paragraphs(text: str) -> str:
    parts = [p.strip() for p in text.split("\n") if p.strip()]
    if not parts:
        return ""
    if len(parts) == 1:
        return f"<p>{html.escape(parts[0])}</p>"
    return "".join(f"<p>{html.escape(p)}</p>" for p in parts)


def _escape_and_trim(text: str, max_len: int) -> str:
    safe = html.escape(text.strip())
    if len(safe) <= max_len:
        return safe
    return safe[: max_len - 1] + "..."


def _hero_block(title: str, analysis: PresentationAnalysis) -> str:
    return f"""
<header class=\"hero\">
  <div>
    <h1>{html.escape(title)}</h1>
    <p>Source file: {html.escape(analysis.source_path)}</p>
  </div>
  <div class=\"hero-actions\">
    <button class=\"btn\" onclick=\"window.print()\">Print</button>
    <button class=\"btn\" onclick=\"toggleTheme()\">Dark mode</button>
    <button class=\"btn\" onclick=\"togglePresentation()\">Presentation mode</button>
    <button class=\"btn\" onclick=\"toggleSnap()\">Scroll snap</button>
    <button class=\"btn\" onclick=\"toggleFullScreen()\">Fullscreen</button>
  </div>
</header>
"""


def _sidebar_shell(nav: str) -> str:
    return f"""
<aside class=\"sidebar\">
  <h2>Index</h2>
  <nav>{nav}</nav>
  <div class=\"progress-wrap\"><div id=\"progress\"></div></div>
  <button class=\"btn small\" onclick=\"window.scrollTo({{top:0,behavior:'smooth'}})\">Back to top</button>
</aside>
"""


def _footer(analysis: PresentationAnalysis) -> str:
    return f"""
<footer class=\"footer\">
  <div>Generated by PIE Mission Manager</div>
  <div>Slides: {analysis.slide_count}</div>
</footer>
"""


def _ai_panel() -> str:
    return """
<aside class='ai-panel'>
  <h3>AI Command Layer</h3>
  <p>Commands are executed by the embedded Mission Manager client.</p>
  <input id='aiInput' type='text' placeholder='e.g. reduce text, add animations, translate' />
  <button class='btn' onclick='runAiCommand()'>Run</button>
  <div id='aiLog'></div>
</aside>
"""


def _shared_ui_css() -> str:
    return """
.sidebar {
  position: fixed;
  top: 0;
  left: 0;
  width: 280px;
  height: 100vh;
  padding: 1rem;
  background: color-mix(in srgb, var(--pie-color-surface) 88%, white 12%);
  border-right: 1px solid var(--pie-color-border);
  overflow-y: auto;
}
.toc-item { display: block; padding: 0.45rem 0.5rem; border-radius: 8px; color: var(--pie-color-text); text-decoration: none; }
.toc-item.active { background: color-mix(in srgb, var(--pie-color-primary) 22%, transparent); }
.hero { display: flex; justify-content: space-between; align-items: center; gap: 1rem; margin-bottom: 1rem; }
.hero h1 { margin: 0; font-size: clamp(1.4rem, 2.4vw, 2.2rem); color: var(--pie-color-primary); }
.hero-actions { display: flex; flex-wrap: wrap; gap: 0.5rem; }
.btn { border: 1px solid var(--pie-color-border); background: var(--pie-color-surface); color: var(--pie-color-text); border-radius: 8px; padding: 0.5rem 0.75rem; cursor: pointer; }
.btn:hover { border-color: var(--pie-color-primary); }
.btn.small { width: 100%; margin-top: 1rem; }
.btn.tiny { padding: 0.25rem 0.5rem; font-size: 0.8rem; }
.section-card { border: 1px solid var(--pie-color-border); border-radius: 14px; background: color-mix(in srgb, var(--pie-color-surface) 90%, white 10%); padding: 1rem 1.2rem; margin-bottom: 1rem; box-shadow: var(--pie-shadow); }
.section-card.slide { min-height: 52vh; }
.sections[data-scroll-snap='on'] .slide { scroll-snap-align: start; }
.sections[data-scroll-snap='on'] { scroll-snap-type: y proximity; }
.kpis { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 0.75rem; }
.kpi { background: color-mix(in srgb, var(--pie-color-primary) 8%, white 92%); border-radius: 10px; border: 1px solid var(--pie-color-border); padding: 0.75rem; }
.kpi span { display: block; font-size: 0.8rem; opacity: 0.8; }
.kpi strong { font-size: 1.2rem; color: var(--pie-color-primary); }
.chips { display: flex; flex-wrap: wrap; gap: 0.35rem; margin-top: 0.75rem; }
.chip { font-size: 0.75rem; border: 1px solid var(--pie-color-border); padding: 0.2rem 0.45rem; border-radius: 999px; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 0.75rem; }
.card { border: 1px solid var(--pie-color-border); border-radius: 12px; padding: 0.75rem; background: color-mix(in srgb, var(--pie-color-surface) 86%, white 14%); }
.image img, .card.image img { width: 100%; height: auto; border-radius: 10px; }
.table-wrap { overflow-x: auto; }
table { width: 100%; border-collapse: collapse; }
th, td { border-bottom: 1px solid var(--pie-color-border); padding: 0.4rem; text-align: left; }
svg.chart { width: 100%; max-width: 560px; height: auto; }
svg.chart rect { fill: var(--pie-color-accent); }
svg.chart line { stroke: var(--pie-color-border); stroke-width: 2; }
.progress-wrap { width: 100%; height: 6px; background: #d2dae6; border-radius: 999px; margin-top: 1rem; overflow: hidden; }
#progress { width: 0%; height: 100%; background: linear-gradient(90deg, var(--pie-color-primary), var(--pie-color-accent)); }
.footer { margin-top: 2rem; padding: 1rem 0; border-top: 1px solid var(--pie-color-border); display: flex; justify-content: space-between; }
.breadcrumb { font-size: 0.82rem; opacity: 0.7; margin-bottom: 0.55rem; }
.ai-panel {
  position: fixed;
  right: 0;
  top: 0;
  width: 290px;
  height: 100vh;
  border-left: 1px solid var(--pie-color-border);
  background: color-mix(in srgb, var(--pie-color-surface) 88%, white 12%);
  padding: 1rem;
  overflow-y: auto;
}
.ai-panel input { width: 100%; padding: 0.5rem; border-radius: 8px; border: 1px solid var(--pie-color-border); margin-bottom: 0.5rem; }
.ai-panel #aiLog { font-size: 0.82rem; margin-top: 0.5rem; white-space: pre-wrap; }
@media (max-width: 1400px) { .ai-panel { display: none; } }
@media (max-width: 980px) {
  .sidebar { position: sticky; width: auto; height: auto; border-right: none; border-bottom: 1px solid var(--pie-color-border); }
}
body.presentation .sidebar, body.presentation .ai-panel { display: none; }
body.presentation main { margin: 0; padding: 0.5rem; }
"""


def _ui_scripts() -> str:
    return """
<script>
const sections = Array.from(document.querySelectorAll('.slide'));
const tocLinks = Array.from(document.querySelectorAll('.toc-item'));

function updateActiveToc() {
  let active = null;
  for (const sec of sections) {
    const rect = sec.getBoundingClientRect();
    if (rect.top <= 180 && rect.bottom >= 180) {
      active = sec.id;
      break;
    }
  }
  tocLinks.forEach((a) => a.classList.toggle('active', a.dataset.target === active));
}

function updateProgress() {
  const total = document.body.scrollHeight - window.innerHeight;
  const pct = total > 0 ? (window.scrollY / total) * 100 : 0;
  document.getElementById('progress').style.width = pct.toFixed(1) + '%';
}

function toggleTheme() {
  const root = document.documentElement;
  root.dataset.theme = root.dataset.theme === 'dark' ? 'light' : 'dark';
}

function togglePresentation() {
  document.body.classList.toggle('presentation');
}

function toggleSnap() {
  const sectionsWrap = document.querySelector('.sections');
  if (!sectionsWrap) return;
  const current = sectionsWrap.getAttribute('data-scroll-snap');
  sectionsWrap.setAttribute('data-scroll-snap', current === 'on' ? 'off' : 'on');
}

function toggleFullScreen() {
  if (!document.fullscreenElement) {
    document.documentElement.requestFullscreen();
  } else {
    document.exitFullscreen();
  }
}

function pieSortTable(button) {
  const table = button.parentElement.nextElementSibling.querySelector('table');
  if (!table) return;
  const rows = Array.from(table.tBodies[0].rows);
  const asc = !table.dataset.asc || table.dataset.asc === '0';
  rows.sort((a,b) => {
    const x = a.cells[0].innerText.trim();
    const y = b.cells[0].innerText.trim();
    return asc ? x.localeCompare(y, undefined, {numeric:true}) : y.localeCompare(x, undefined, {numeric:true});
  });
  table.dataset.asc = asc ? '1' : '0';
  rows.forEach(r => table.tBodies[0].appendChild(r));
}

function pieExportTable(button, rows) {
  const csv = rows.map(r => r.map(cell => '"' + String(cell).replaceAll('"', '""') + '"').join(',')).join('\n');
  const blob = new Blob([csv], {type: 'text/csv'});
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'table_export.csv';
  a.click();
  URL.revokeObjectURL(a.href);
}

function runAiCommand() {
  const input = document.getElementById('aiInput');
  const log = document.getElementById('aiLog');
  const command = (input.value || '').trim().toLowerCase();
  if (!command) return;

  if (command.includes('reduce text') || command.includes('reduce')) {
    document.querySelectorAll('p').forEach((p) => {
      if (p.innerText.length > 280) p.innerText = p.innerText.slice(0, 280) + '...';
    });
    log.innerText += '\n- Mission Manager: Text reduction applied.';
  } else if (command.includes('cards')) {
    document.querySelectorAll('.element.text').forEach((el) => el.classList.add('card'));
    log.innerText += '\n- Mission Manager: Converted text blocks into card styling.';
  } else if (command.includes('animations') || command.includes('visual')) {
    document.querySelectorAll('.section-card').forEach((el, i) => {
      el.style.animation = `fadeIn 350ms ease ${i * 50}ms both`;
    });
    log.innerText += '\n- Mission Manager: Visual animation profile enabled.';
  } else if (command.includes('translate')) {
    log.innerText += '\n- Mission Manager: Translation request captured (hook for server-side pipeline).';
  } else {
    log.innerText += '\n- Mission Manager: Command captured, no direct local transform mapped.';
  }

  input.value = '';
}

window.addEventListener('scroll', () => { updateProgress(); updateActiveToc(); });
window.addEventListener('load', () => { updateProgress(); updateActiveToc(); });
</script>
<style>@keyframes fadeIn { from {opacity:0; transform: translateY(8px);} to {opacity:1; transform: translateY(0);} }</style>
"""
