[theme]
primaryColor = "#FF6A00"
backgroundColor = "#0D0F13"
secondaryBackgroundColor = "#161920"
textColor = "#F2F3F5"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = true

[browser]
gatherUsageStats = false
